In [99]:
import numpy as np
from sklearn.cross_decomposition import PLSRegression
from sklearn import preprocessing
X = np.array([[7,7,13,7],[4,3,14,7],[10,5,12,5],[16,7,11,3],[13,3,10,3]])
Y = np.array([[14,7,8],[10,7,6],[8,5,5],[2,4,7],[6,2,4]])
X_scaled = preprocessing.scale(X)
Y_scaled = preprocessing.scale(Y)
pls2 = PLSRegression(n_components=3)
pls2.fit(X,Y)
T = pls2.x_scores_
P = pls2.x_loadings_
U = pls2.y_scores_
Q = pls2.y_loadings_
W = pls2.x_weights_
C = pls2.y_weights_
X_hat = np.dot(T, P.T)
Y_hat = np.dot(U, Q.T)
print(X)
print(Y)
print(X_scaled)
print(Y_scaled)
print(X_hat)
print(Y_hat)

[[ 7  7 13  7]
 [ 4  3 14  7]
 [10  5 12  5]
 [16  7 11  3]
 [13  3 10  3]]
[[14  7  8]
 [10  7  6]
 [ 8  5  5]
 [ 2  4  7]
 [ 6  2  4]]
[[-0.71  1.12  0.71  1.12]
 [-1.41 -1.12  1.41  1.12]
 [ 0.    0.    0.    0.  ]
 [ 1.41  1.12 -0.71 -1.12]
 [ 0.71 -1.12 -1.41 -1.12]]
[[ 1.5   1.05  1.41]
 [ 0.5   1.05  0.  ]
 [ 0.    0.   -0.71]
 [-1.5  -0.53  0.71]
 [-0.5  -1.58 -1.41]]
[[-0.63  1.    0.63  1.  ]
 [-1.26 -1.    1.26  1.  ]
 [ 0.    0.    0.    0.  ]
 [ 1.26  1.   -0.63 -1.  ]
 [ 0.63 -1.   -1.26 -1.  ]]
[[ 1.74  1.44  1.37]
 [ 0.08  0.63 -0.1 ]
 [-0.03 -0.34 -0.68]
 [-1.21 -0.2   0.86]
 [-0.58 -1.52 -1.45]]


/home/jay/anaconda3/envs/python3/lib/python3.5/site-packages/sklearn/utils/validation.py:429: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, _DataConversionWarning)


In [106]:
np.set_printoptions(precision=2)
print(np.dot(T.T, T))
print(np.dot(W.T, W))

[[  1.09e+01  -4.44e-16  -5.00e-16]
 [ -4.44e-16   4.46e+00   0.00e+00]
 [ -5.00e-16   0.00e+00   2.65e-01]]
[[  1.00e+00   7.63e-17  -1.67e-16]
 [  7.63e-17   1.00e+00  -4.16e-17]
 [ -1.67e-16  -4.16e-17   1.00e+00]]


In [96]:
print(np.dot(X_scaled, W[:,0]) / T[:,0])
print(np.dot(Y_scaled, C[:,0]) / U[:,0])

[ 1.12  1.12   nan  1.12  1.12]
[ 0.78  0.78  0.78  0.78  0.78]


/home/jay/anaconda3/envs/python3/lib/python3.5/site-packages/ipykernel/__main__.py:3: RuntimeWarning: invalid value encountered in true_divide
  app.launch_new_instance()


(array([[ 1.5 ,  0.98, -0.29],
        [ 1.78, -1.04,  0.24],
        [ 0.  ,  0.  ,  0.  ],
        [-1.42,  1.12,  0.27],
        [-1.86, -1.07, -0.22]]), array([[ 2.32,  0.99, -0.28],
        [ 1.12, -0.69,  0.25],
        [-0.28, -0.79, -0.04],
        [-1.09,  1.5 ,  0.28],
        [-2.07, -1.01, -0.21]]))

In [108]:
print(T)
print(U)

[[ 1.5   0.98 -0.29]
 [ 1.78 -1.04  0.24]
 [ 0.    0.    0.  ]
 [-1.42  1.12  0.27]
 [-1.86 -1.07 -0.22]]
[[ 2.32  0.99 -0.28]
 [ 1.12 -0.69  0.25]
 [-0.28 -0.79 -0.04]
 [-1.09  1.5   0.28]
 [-2.07 -1.01 -0.21]]


In [80]:
(np.dot(C[:,0].T,C[:,0]) * U[:,0]+np.dot(C[:,1].T,C[:,0])*U[:,1]+ np.dot(C[:,2].T,C[:,0])*U[:,2])/U[:,0]

array([ 0.93,  0.34,  1.54,  0.43,  0.79])

In [91]:
from sklearn.cross_decomposition import PLSRegression
X = [[0., 0., 1.], [1.,0.,0.], [2.,2.,2.], [2.,5.,4.]]
Y = [[0.1, -0.2], [0.9, 1.1], [6.2, 5.9], [11.9, 12.3]]
pls2 = PLSRegression(n_components=2)
pls2.fit(X, Y)
Y_pred = pls2.predict(X)
Y_pred

array([[ 1.53,  1.48],
       [ 2.43,  2.36],
       [ 6.26,  6.27],
       [ 8.88,  9.  ]])